import { dirname } from "node:path";
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-plugin-prettier";
import betterTailwindcss from "eslint-plugin-better-tailwindcss";
import storybook from "eslint-plugin-storybook";
import unicorn from "eslint-plugin-unicorn";
import testingLibrary from "eslint-plugin-testing-library";
import jestDom from "eslint-plugin-jest-dom";
import jsxA11y from "eslint-plugin-jsx-a11y";
import playwright from "eslint-plugin-playwright";
import reactHooks from "eslint-plugin-react-hooks";
import react from "eslint-plugin-react";
import next from "@next/eslint-plugin-next";
import importPlugin from "eslint-plugin-import";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import tailwindDisableReason from "./eslint-rules/tailwind-disable-reason.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: eslint.configs.recommended,
});

export default [
  {
    ignores: [
      "public/next-assets/webApplicationInjector.js",
      "public/next-assets/scripts/omid/omid-session-client-v1.js",
      "public/next-assets/scripts/omid/omweb-v1.js",
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  ...tseslint.configs.strict,
  ...tseslint.configs.stylistic,
  {
    plugins: { "@next/next": next },
    rules: {
      ...next.configs.recommended.rules,
      ...next.configs["core-web-vitals"].rules,
      "@next/next/no-html-link-for-pages": "off",
    },
  },
  {
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },
  betterTailwindcss.configs["correctness-error"],
  ...storybook.configs["flat/recommended"],
  ...compat.config({}),
  {
    plugins: {
      import: importPlugin,
      unicorn,
      "testing-library": testingLibrary,
      "jest-dom": jestDom,
      react,
      "jsx-a11y": jsxA11y,
      "tailwind-disable-reason": tailwindDisableReason,
    },
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
      },
    },
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@next/next/no-html-link-for-pages": "off",
      "@typescript-eslint/array-type": ["error", { default: "generic" }],
      "@typescript-eslint/naming-convention": [
        "warn",
        { selector: ["enum", "enumMember"], format: ["UPPER_CASE"] },
        { selector: ["interface", "class"], format: ["PascalCase"] },
        { selector: ["variable", "classMethod"], format: ["camelCase"] },
        {
          selector: "parameter",
          format: ["PascalCase", "camelCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: ["variable"],
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
          modifiers: ["const"],
        },
        {
          selector: ["variable"],
          format: ["camelCase", "PascalCase"],
          modifiers: ["destructured"],
        },
        {
          selector: "function",
          format: ["camelCase", "PascalCase"],
          prefix: [
            "get",
            "set",
            "fetch",
            "create",
            "generate",
            "normalize",
            "serialize",
            "handle",
            "use",
            "with",
            "has",
            "is",
          ],
          filter: { regex: "^[a-z]", match: true },
        },
        {
          selector: ["variable"],
          format: ["camelCase", "PascalCase"],
          prefix: ["should", "has", "is"],
          types: ["boolean"],
          filter: { regex: "^value$", match: false },
        },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { caughtErrors: "all", caughtErrorsIgnorePattern: "^ignore" },
      ],
      "consistent-return": "error",
      "import/no-default-export": "error",
      "import/no-extraneous-dependencies": "error",
      "import/order": [
        "error",
        {
          alphabetize: {
            order: "asc",
            caseInsensitive: true,
          },
          "newlines-between": "never",
          groups: [
            "external",
            "builtin",
            "internal",
            ["sibling", "parent"],
            "index",
          ],
        },
      ],
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/heading-has-content": "error",
      "jsx-a11y/img-redundant-alt": "error",
      "jsx-a11y/no-redundant-roles": "error",
      "jsx-quotes": ["error", "prefer-double"],
      "lines-around-directive": "error",
      "newline-before-return": "error",
      "no-case-declarations": "off",
      "no-console": "error",
      "no-duplicate-imports": "error",
      "no-implicit-coercion": "error",
      "no-prototype-builtins": "warn",
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "usehooks-ts",
              importNames: ["useLocalStorage"],
              message: 'use "~/hooks/use-local-storage" instead.',
            },
            {
              name: "next/link",
              message: "Please use Link from @components instead.",
            },
            {
              name: "next/image",
              message: "Please use Image from @components instead.",
            },
            {
              name: "react",
              importNames: ["default"],
              message: "Use named imports instead",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "warn",
        {
          selector: "JSXOpeningElement[name.name='h1']",
          message:
            "Usage of <h1> tags is prohibited. Please use the Heading component.",
        },
        {
          selector: "JSXOpeningElement[name.name='h2']",
          message:
            "Usage of <h2> tags is prohibited. Please use the Heading component.",
        },
        {
          selector: "JSXOpeningElement[name.name='h3']",
          message:
            "Usage of <h3> tags is prohibited. Please use the Heading component.",
        },
        {
          selector: "JSXOpeningElement[name.name='h4']",
          message:
            "Usage of <h4> tags is prohibited. Please use the Heading component.",
        },
      ],
      "no-useless-escape": "error",
      "prefer-destructuring": "error",
      "prettier/prettier": "error",
      "react/boolean-prop-naming": [
        "warn",
        { rule: "^(is|has|should)[A-Z]([A-Za-z0-9]?)+" },
      ],
      "react/button-has-type": "error",
      "react/destructuring-assignment": ["error", "always"],
      "react/display-name": ["off", { ignoreTranspilerName: false }],
      "react/forbid-component-props": [
        "warn",
        {
          forbid: [
            {
              propName: "className",
              allowedFor: [
                "Icon",
                "Link",
                "Dialog",
                "Dialog.Panel",
                "Image",
                "FormattedPrice",
                "NavLink",
                "NextLink",
                "Component",
                "SearchInput",
                "CarouselItem",
                "Skeleton",
                "ProductCard",
                "Listbox.Button",
                "Listbox.Options",
                "Listbox.Option",
                "Listbox.Label",
                "Disclosure",
                "DisclosureButton",
                "DisclosurePanel",
                "VaulDrawer.Root",
                "VaulDrawer.Trigger",
                "VaulDrawer.Portal",
                "VaulDrawer.Overlay",
                "VaulDrawer.Content",
                "VaulDrawer.Handle",
                "VaulDrawer.Title",
                "VaulDrawer.Description",
                "VaulDrawer.Close",
              ],
              message: "Avoid using className",
            },
          ],
        },
      ],
      "react/function-component-definition": [
        "error",
        { namedComponents: "function-declaration" },
      ],
      "react/jsx-boolean-value": ["error", "never", { always: [] }],
      "react/jsx-child-element-spacing": "off",
      "react/jsx-curly-brace-presence": "error",
      "react/jsx-curly-spacing": ["error", "never", { allowMultiline: true }],
      "react/jsx-fragments": ["error", "syntax"],
      "react/jsx-handler-names": [
        "off",
        { eventHandlerPrefix: "handle", eventHandlerPropPrefix: "on" },
      ],
      "react/jsx-indent-props": ["error", 2],
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-pascal-case": ["error", { allowAllCaps: true, ignore: [] }],
      "react/jsx-props-no-multi-spaces": "error",
      "react/no-invalid-html-attribute": "error",
      "react/no-unstable-nested-components": ["error", { allowAsProps: true }],
      "react/no-unsafe": "off",
      "react/self-closing-comp": ["error", { component: true, html: true }],
      "react/sort-default-props": ["off", { ignoreCase: false }],
      "sonarjs/array-callback-without-return": "off",
      "sonarjs/cognitive-complexity": "off",
      "sonarjs/collection-size": "off",
      "sonarjs/conditional-indentation": "off",
      "sonarjs/default-param-last": "off",
      "sonarjs/deprecation": "off",
      "sonarjs/different-types-comparison": "off",
      "sonarjs/fixme-tag": "off",
      "sonarjs/function-return-type": "off",
      "sonarjs/hook-use-state": "off",
      "sonarjs/jsx-no-constructed-context-values": "off",
      "sonarjs/max-switch-cases": "off",
      "sonarjs/mouse-events-a11y": "off",
      "sonarjs/new-cap": "off",
      "sonarjs/no-all-duplicated-branches": "off",
      "sonarjs/no-array-index-key": "off",
      "sonarjs/no-base-to-string": "off",
      "sonarjs/no-clear-text-protocols": "off",
      "sonarjs/no-collapsible-if": "off",
      "sonarjs/no-collection-size-mischeck": "off",
      "sonarjs/no-duplicate-string": "off",
      "sonarjs/no-duplicated-branches": "off",
      "sonarjs/no-element-overwrite": "off",
      "sonarjs/no-empty-alternatives": "off",
      "sonarjs/no-empty-collection": "off",
      "sonarjs/no-extra-arguments": "off",
      "sonarjs/no-globals-shadowing": "off",
      "sonarjs/no-gratuitous-expressions": "off",
      "sonarjs/no-hardcoded-credentials": "off",
      "sonarjs/no-identical-conditions": "off",
      "sonarjs/no-identical-expressions": "off",
      "sonarjs/no-identical-functions": "off",
      "sonarjs/no-ignored-exceptions": "off",
      "sonarjs/no-ignored-return": "off",
      "sonarjs/no-incomplete-assertions": "off",
      "sonarjs/no-intrusive-permissions": "off",
      "sonarjs/no-invalid-await": "off",
      "sonarjs/no-inverted-boolean-check": "off",
      "sonarjs/no-misleading-array-reverse": "off",
      "sonarjs/no-misused-promises": "off",
      "sonarjs/no-nested-assignment": "off",
      "sonarjs/no-nested-conditional": "off",
      "sonarjs/no-nested-functions": "off",
      "sonarjs/no-one-iteration-loop": "off",
      "sonarjs/no-redundant-boolean": "off",
      "sonarjs/no-redundant-jump": "off",
      "sonarjs/no-redundant-optional": "off",
      "sonarjs/no-redundant-type-aliases": "off",
      "sonarjs/no-redundant-type-constituents": "off",
      "sonarjs/no-same-line-conditional": "off",
      "sonarjs/no-self-import": "off",
      "sonarjs/no-selector-parameter": "off",
      "sonarjs/no-skipped-test": "off",
      "sonarjs/no-small-switch": "off",
      "sonarjs/no-try-promise": "off",
      "sonarjs/no-undefined-argument": "off",
      "sonarjs/no-unstable-nested-components": "off",
      "sonarjs/no-unused-collection": "off",
      "sonarjs/no-use-of-empty-return-value": "off",
      "sonarjs/non-existent-operator": "off",
      "sonarjs/prefer-immediate-return": "off",
      "sonarjs/prefer-nullish-coalescing": "off",
      "sonarjs/prefer-object-spread": "off",
      "sonarjs/prefer-single-boolean-return": "off",
      "sonarjs/prefer-while": "off",
      "sonarjs/pseudo-random": "off",
      "sonarjs/regex-complexity": "off",
      "sonarjs/redundant-type-aliases": "off",
      "sonarjs/rules-of-hooks": "off",
      "sonarjs/slow-regex": "off",
      "sonarjs/sonar-max-params": "off",
      "sonarjs/sonar-no-unused-vars": "off",
      "sonarjs/sonar-prefer-optional-chain": "off",
      "sonarjs/sonar-prefer-read-only-props": "off",
      "sonarjs/sonar-prefer-regexp-exec": "off",
      "sonarjs/todo-tag": "off",
      "sonarjs/prefer-read-only-props": "off",
      "sonarjs/no-hardcoded-passwords": "off",
      "sonarjs/prefer-regexp-exec": "off",
      "sonarjs/no-unused-vars": "off",
      "sonarjs/no-skipped-tests": "off",
      "sonarjs/no-hardcoded-secrets": "off",
      "sonarjs/no-commented-code": "off",
      "better-tailwindcss/enforce-consistent-class-order": [
        "error",
        {
          tailwindConfig: "./tailwind.config.ts",
          tsconfig: "./tsconfig.json",
          entryPoint: "./src/app/theme.css",
        },
      ],
      "better-tailwindcss/enforce-consistent-line-wrapping": "off",
      "better-tailwindcss/no-conflicting-classes": [
        "error",
        {
          tailwindConfig: "./tailwind.config.ts",
          tsconfig: "./tsconfig.json",
          entryPoint: "./src/app/theme.css",
          detectComponentClasses: false,
        },
      ],
      "better-tailwindcss/no-restricted-classes": [
        "error",
        {
          restrict: [
            {
              pattern: "\\[.+\\]",
              message:
                "Arbitrary values are forbidden. Use a design token or, if not present, create a new one in accordance to UX guidelines.",
            },
          ],
        },
      ],
      "better-tailwindcss/no-unknown-classes": [
        "error",
        {
          tailwindConfig: "./tailwind.config.ts",
          tsconfig: "./tsconfig.json",
          entryPoint: "./src/app/theme.css",
          detectComponentClasses: false,
          ignore: [
            "smartEditComponent",
            "no-scrollbar",
            "underscore-show",
            "underscore-hide",
            "dir-rtl",
            "dir-ltr",
            "sidebar-container-breakout",
            "checkout-sidebar",
            "mx-break-out",
            "pl-break-out",
            "transition-default",
            "safari-line-clamp-block",
            "comparison-v2-header-wrapper",
            "is-compact",
            "comparison-v2-card",
            "comparison-v2-hide-when-compact",
            "comparison-v2-image",
            "comparison-v2-show-when-compact",
          ],
        },
      ],
      "tailwind-disable-reason/require-why": "error",
      "testing-library/consistent-data-testid": [
        "warn",
        { testIdPattern: "^TEST_ID.?$" },
      ],
      "unicorn/better-regex": "warn",
      "unicorn/catch-error-name": "error",
      "unicorn/consistent-destructuring": "warn",
      "unicorn/custom-error-definition": "error",
      "unicorn/error-message": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/filename-case": [
        "error",
        {
          cases: { kebabCase: true, pascalCase: false },
          ignore: ["^\\.README\\.md$"],
        },
      ],
      "unicorn/no-document-cookie": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-lonely-if": "error",
      "unicorn/no-typeof-undefined": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-export-from": "error",
    },
  },
  {
    ...playwright.configs["flat/recommended"],
    files: ["**/playwright/**"],
    rules: {
      "playwright/expect-expect": "off",
      "playwright/no-networkidle": "warn",
      "playwright/no-conditional-expect": "off",
      "react-hooks/rules-of-hooks": "off",
      "unicorn/consistent-function-scoping": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-floating-promises": "error",
    },
  },
  {
    files: ["**/*.stories.tsx"],
    rules: {
      "no-restricted-syntax": ["off"],
      "react-hooks/rules-of-hooks": ["off"],
    },
  },
  {
    files: ["**/constants/**"],
    rules: {
      "@typescript-eslint/naming-convention": [
        "error",
        { selector: ["variable"], format: ["UPPER_CASE"] },
      ],
    },
  },
  {
    files: [
      "**/page.tsx",
      "**/layout.tsx",
      "**/route.ts",
      "**/loading.tsx",
      "**/not-found.tsx",
      "**/*.config.*",
      "**/error.tsx",
      "**/global-error.tsx",
      "**/*.stories.tsx",
    ],
    rules: {
      "import/no-default-export": "off",
    },
  },
  {
    plugins: { prettier },
    rules: {
      "prettier/prettier": "error",
    },
  },
];
